### ISSUE TITLE
Content Assist: error while query symbols in unloaded modules

### ISSUE THREAD

**Issue by NCrashed** [bruno-medeiros/DDT#97]
Version:   DDT - D Development Tools	0.11.0.v201503062245

If you call completion on symbols in another module and the modules haven't been opened at least once in editor before, you get the following error:

![ddt-problem](https://cloud.githubusercontent.com/assets/2116167/6540924/340e609a-c4d1-11e4-86aa-9a4b5d49b413.png)

Last exception in log:
```
!ENTRY org.dsource.ddt.ide.core 4 0 2015-03-07 12:46:20.846
!MESSAGE Internal Error
!STACK 0
AssertFailedException
	at melnorme.utilbox.core.Assert$AssertHandler.handleAssert(Assert.java:60)
	at melnorme.utilbox.core.Assert.checkAssertion(Assert.java:87)
	at melnorme.utilbox.core.Assert$AssertNamespace.assertTrue(Assert.java:149)
	at melnorme.lang.tooling.ast.ASTNodeFinder.<init>(ASTNodeFinder.java:53)
	at melnorme.lang.tooling.ast.ASTNodeFinder.<init>(ASTNodeFinder.java:42)
	at dtool.engine.operations.FindDefinitionOperation.findDefinition(FindDefinitionOperation.java:65)
	at dtool.engine.operations.FindDefinitionOperation.findDefinition(FindDefinitionOperation.java:60)
	at dtool.engine.DToolServer.doFindDefinition(DToolServer.java:92)
	at mmrnmhrm.core.engine_client.DToolClient.doFindDefinition(DToolClient.java:265)
	at mmrnmhrm.core.engine_client.DToolClient$FindDefinitionOperation.doRunOperationWithWorkingCopy(DToolClient.java:234)
	at mmrnmhrm.core.engine_client.DToolClient$FindDefinitionOperation.doRunOperationWithWorkingCopy(DToolClient.java:1)
	at mmrnmhrm.core.engine_client.AbstractSemanticDaemonClient$SemanticEngineOperation.runOperationWithWorkingCopy(AbstractSemanticDaemonClient.java:168)
	at mmrnmhrm.core.engine_client.AbstractSemanticDaemonClient$WorkingCopyOperation.runSemanticServerOperation(AbstractSemanticDaemonClient.java:141)
	at mmrnmhrm.ui.actions.DeeOpenDefinitionOperation.performLongRunningComputation_do(DeeOpenDefinitionOperation.java:60)
	at melnorme.lang.ide.ui.actions.AbstractUIOperation.performLongRunningComputation_inWorkerThread(AbstractUIOperation.java:125)
	at melnorme.lang.ide.ui.actions.AbstractUIOperation$1.run(AbstractUIOperation.java:101)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

P.S. I recreated project after updating

**Comment by NCrashed** [comment]
Another way to reproduce: type `this.` (anywhere in block), ignore completion dialog, start pressing `backspace` until there are only two letters `th`, exception raised.

**Comment by NCrashed** [comment]
#99 has instruction for temporary workaround how to downgrade to 10th version

**Comment by bruno-medeiros** [comment]
There's an easier way to revert to previous DDT version, if you had it installed before: Go to `Help/Installation Details/Installation History`, look for the entry where you had 0.10.4.v2014... installed and press Revert:
![eclipserevert](https://cloud.githubusercontent.com/assets/4324232/6666220/2bcb784a-cbda-11e4-8e01-6d0da8c2b0b1.png)

In any case I'm looking into this bug now.
